In [14]:
import geopandas as gpd
import pandas as pd
import numpy as np
import plotly.express as px

In [15]:
camada = gpd.read_file(r"LOTES_SANTO_INACIO\LOTES_SANTOINACIO_.shp",crs = 31984)
nucleo = 'SANTO INACIO DO PIAUI'
cidade = 'SANTO INACIO DO PIAUI'
uf = 'PI'
zona_utm = '24'

c:\Users\karlo\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyogrio\raw.py:198: RuntimeWarning: driver ESRI Shapefile does not support open option CRS
  return ogr_read(

In [16]:
camada.info()
camada.describe()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 1716 entries, 0 to 1715
Data columns (total 24 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   QUADRA      1715 non-null   object
 1   LOTE        1623 non-null   object
 2   fid         0 non-null      float64
 3   BAIRRO      0 non-null      object
 4   PERIMETRO   0 non-null      object
 5   CIDADE      0 non-null      object
 6   AREA_M2     0 non-null      float64
 7   TIPO        1716 non-null   object
 8   NUCLEO      0 non-null      object
 9   UF          0 non-null      object
 10  CONCATENAR  0 non-null      object
 11  NOME        0 non-null      object
 12  DOCUMENTO   0 non-null      object
 13  COMODOS     0 non-null      object
 14  SITUACAO    0 non-null      object
 15  LOGRADOURO  0 non-null      object
 16  NUMERO      0 non-null      object
 17  CADASTRADO  0 non-null      object
 18  AREA CADS   0 non-null      object
 19  OBSERVACAO  513 non-null    object
 20  ZONA_UTM    0 non-null      float64
 21  LOTE_LETRA  0 non-null      object
 22  ID          0 non-null      float64
 23  geometry    1716 non-null   geometry
dtypes: float64(4), geometry(1), object(19)
memory usage: 321.9+ KB

       fid  AREA_M2  ZONA_UTM   ID
count  0.0      0.0       0.0  0.0
mean   NaN      NaN       NaN  NaN
std    NaN      NaN       NaN  NaN
min    NaN      NaN       NaN  NaN
25%    NaN      NaN       NaN  NaN
50%    NaN      NaN       NaN  NaN
75%    NaN      NaN       NaN  NaN
max    NaN      NaN       NaN  NaN

In [17]:
camada.columns

Index(['QUADRA', 'LOTE', 'fid', 'BAIRRO', 'PERIMETRO', 'CIDADE', 'AREA_M2',
       'TIPO', 'NUCLEO', 'UF', 'CONCATENAR', 'NOME', 'DOCUMENTO', 'COMODOS',
       'SITUACAO', 'LOGRADOURO', 'NUMERO', 'CADASTRADO', 'AREA CADS',
       'OBSERVACAO', 'ZONA_UTM', 'LOTE_LETRA', 'ID', 'geometry'],
      dtype='object')

In [18]:
def preencher_campos(camada,nucleo = 'SANTO INACIO DO PIAUI',cidade = 'SANTO INACIO DO PIAUI',uf = 'PI',zona_utm = '24'):
    camada['NUCLEO'] = nucleo
    camada['CIDADE'] = cidade
    camada['UF'] = uf
    camada['ZONA_UTM'] = zona_utm
    camada[['QUADRA', 'LOTE']] = camada[['QUADRA', 'LOTE']].fillna(0)
    camada['AREA_M2'] = camada.area
    camada['PERIMETRO'] = camada.length  

preencher_campos(camada,nucleo,cidade,uf,zona_utm)

In [ ]:
camada

,QUADRA,LOTE,fid,BAIRRO,PERIMETRO,CIDADE,AREA_M2,TIPO,NUCLEO,UF,...,SITUACAO,LOGRADOURO,NUMERO,CADASTRADO,AREA CADS,OBSERVACAO,ZONA_UTM,LOTE_LETRA,ID,geometry
0,49,0,NaN,None,278.101503,SANTO INACIO DO PIAUI,3.977332e+03,QUADRA,SANTO INACIO DO PIAUI,PI,...,None,None,None,None,None,None,24,None,NaN,"POLYGON ((178277.624 9178571.779, 178277.624 9..."
1,46,0,NaN,None,482.352894,SANTO INACIO DO PIAUI,1.249093e+04,QUADRA,SANTO INACIO DO PIAUI,PI,...,None,None,None,None,None,None,24,None,NaN,"POLYGON ((178285.809 9178574.926, 178284.187 9..."
2,50,0,NaN,None,397.845013,SANTO INACIO DO PIAUI,1.014504e+04,QUADRA,SANTO INACIO DO PIAUI,PI,...,None,None,None,None,None,None,24,None,NaN,"POLYGON ((178195.865 9178508.995, 178196.302 9..."
3,51,0,NaN,None,338.868960,SANTO INACIO DO PIAUI,6.920027e+03,QUADRA,SANTO INACIO DO PIAUI,PI,...,None,None,None,None,None,None,24,None,NaN,"POLYGON ((178290.481 9178564.822, 178289.169 9..."
4,54,0,NaN,None,428.093514,SANTO INACIO DO PIAUI,1.146555e+04,QUADRA,SANTO INACIO DO PIAUI,PI,...,None,None,None,None,None,None,24,None,NaN,"POLYGON ((178253.126 9178419.008, 178251.57 91..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1711,36,1,NaN,None,86.253564,SANTO INACIO DO PIAUI,2.792946e+02,LOTE,SANTO INACIO DO PIAUI,PI,...,None,None,None,None,None,VERIFICAR LIMITES,24,None,NaN,"POLYGON ((178057.361 9178919.309, 178052.868 9..."
1712,36,3,NaN,None,96.229750,SANTO INACIO DO PIAUI,3.117968e+02,LOTE,SANTO INACIO DO PIAUI,PI,...,None,None,None,None,None,None,24,None,NaN,"POLYGON ((178025.374 9178897.363, 178064.461 9..."
1713,68,5,NaN,None,43.818726,SANTO INACIO DO PIAUI,7.317238e+01,LOTE,SANTO INACIO DO PIAUI,PI,...,None,None,None,None,None,None,24,None,NaN,"POLYGON ((178545.276 9178119.914, 178527.483 9..."
1714,59,17,NaN,None,80.088693,SANTO INACIO DO PIAUI,2.841010e+02,LOTE,SANTO INACIO DO PIAUI,PI,...,None,None,None,None,None,VERIFICAR LIMITES,24,None,NaN,"POLYGON ((178412.951 9178323.216, 178407.517 9..."
1715,0,0,NaN,None,8138.183341,SANTO INACIO DO PIAUI,4.142758e+06,NUCLEO,SANTO INACIO DO PIAUI,PI,...,None,None,None,None,None,None,24,None,NaN,"POLYGON ((179377.522 9179220.09, 179436.242 91..."

In [20]:
duplicados = camada[camada.duplicated(subset='geometry',keep=False)]
duplicados_nulos = duplicados[ (duplicados['LOTE'].isna())]

# Remover registros duplicados onde o campo 'LOTE' é nulo
camada = camada.drop(duplicados_nulos.index)

In [21]:
# duplicados = camada[camada['geometry'].duplicated(keep=False)]

duplicados

Empty GeoDataFrame
Columns: [QUADRA, LOTE, fid, BAIRRO, PERIMETRO, CIDADE, AREA_M2, TIPO, NUCLEO, UF, CONCATENAR, NOME, DOCUMENTO, COMODOS, SITUACAO, LOGRADOURO, NUMERO, CADASTRADO, AREA CADS, OBSERVACAO, ZONA_UTM, LOTE_LETRA, ID, geometry]
Index: []

[0 rows x 24 columns]

In [22]:
# Transformar cada polígono em sua linha de contorno
linhas = camada.copy()
linhas['geometry'] = camada.boundary

In [44]:
# Selecionar elementos que possuem valores preenchidos na coluna 'QUADRA'
gdf_preenchidos = linhas[linhas['OBSERVACAO'].notnull()  | (linhas['TIPO'] == 'NUCLEO')]
gdf_n_preenchidos = linhas[linhas['OBSERVACAO'].isnull() | (linhas['TIPO'] == 'NUCLEO')]
gdf_n_preenchidos

,QUADRA,LOTE,fid,BAIRRO,PERIMETRO,CIDADE,AREA_M2,TIPO,NUCLEO,UF,...,SITUACAO,LOGRADOURO,NUMERO,CADASTRADO,AREA CADS,OBSERVACAO,ZONA_UTM,LOTE_LETRA,ID,geometry
0,49,0,NaN,None,278.101503,SANTO INACIO DO PIAUI,3.977332e+03,QUADRA,SANTO INACIO DO PIAUI,PI,...,None,None,None,None,None,None,24,None,NaN,"LINESTRING (178277.624 9178571.779, 178277.624..."
1,46,0,NaN,None,482.352894,SANTO INACIO DO PIAUI,1.249093e+04,QUADRA,SANTO INACIO DO PIAUI,PI,...,None,None,None,None,None,None,24,None,NaN,"LINESTRING (178285.809 9178574.926, 178284.187..."
2,50,0,NaN,None,397.845013,SANTO INACIO DO PIAUI,1.014504e+04,QUADRA,SANTO INACIO DO PIAUI,PI,...,None,None,None,None,None,None,24,None,NaN,"LINESTRING (178195.865 9178508.995, 178196.302..."
3,51,0,NaN,None,338.868960,SANTO INACIO DO PIAUI,6.920027e+03,QUADRA,SANTO INACIO DO PIAUI,PI,...,None,None,None,None,None,None,24,None,NaN,"LINESTRING (178290.481 9178564.822, 178289.169..."
4,54,0,NaN,None,428.093514,SANTO INACIO DO PIAUI,1.146555e+04,QUADRA,SANTO INACIO DO PIAUI,PI,...,None,None,None,None,None,None,24,None,NaN,"LINESTRING (178253.126 9178419.008, 178251.57 ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1709,58,0,NaN,None,1769.926751,SANTO INACIO DO PIAUI,1.832134e+05,QUADRA,SANTO INACIO DO PIAUI,PI,...,None,None,None,None,None,None,24,None,NaN,"LINESTRING (178487.199 9178710.686, 178486.209..."
1710,35,0,NaN,None,1161.266499,SANTO INACIO DO PIAUI,5.618669e+04,QUADRA,SANTO INACIO DO PIAUI,PI,...,None,None,None,None,None,None,24,None,NaN,"LINESTRING (177696.55 9178768.619, 177691.377 ..."
1712,36,3,NaN,None,96.229750,SANTO INACIO DO PIAUI,3.117968e+02,LOTE,SANTO INACIO DO PIAUI,PI,...,None,None,None,None,None,None,24,None,NaN,"LINESTRING (178025.374 9178897.363, 178064.461..."
1713,68,5,NaN,None,43.818726,SANTO INACIO DO PIAUI,7.317238e+01,LOTE,SANTO INACIO DO PIAUI,PI,...,None,None,None,None,None,None,24,None,NaN,"LINESTRING (178545.276 9178119.914, 178527.483..."
1715,0,0,NaN,None,8138.183341,SANTO INACIO DO PIAUI,4.142758e+06,NUCLEO,SANTO INACIO DO PIAUI,PI,...,None,None,None,None,None,None,24,None,NaN,"LINESTRING (179377.522 9179220.09, 179436.242 ..."

In [45]:
path = str(r"LOTES_SANTO_INACIO\enviar\SANTOINACIOAPOIO06112024.shp")
print(path)

LOTES_SANTO_INACIO\enviar\SANTOINACIOAPOIO06112024.shp

In [46]:
gdf_preenchidos.to_file(r"LOTES_SANTO_INACIO\enviar\SANTOINACIOAPOIO06112024.shp")
gdf_n_preenchidos.to_file(r"LOTES_SANTO_INACIO\enviar\SANTOINACIO06112024.shp")

In [47]:
camada.to_file(r"LOTES_SANTO_INACIO\enviar\SANTOINACIO06112024_poligono.shp")
duplicados_nulos.to_file(r"LOTES_SANTO_INACIO\enviar\duplicados.shp")